package gui.panels.server_manager_panel;

import gui.panels.server_manager_panel.cards.EditServerCard;
import gui.panels.server_manager_panel.cards.ServerCard;
import settings.ServerSettings;
import settings.ServerSettings.ServerCardSettings;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Properties;
import java.util.Set;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

public class SMLogic {

    private final ConcurrentHashMap<String, Process> runningProcesses = new ConcurrentHashMap<>();
    private final Set<String> activeLogReaders = ConcurrentHashMap.newKeySet(); // ← защита от двойного запуска
    private final ConcurrentHashMap<String, StringBuilder> serverLogs = new ConcurrentHashMap<>(); // ← сохранение логов
    private final ConcurrentHashMap<String, PrintWriter> processInputs = new ConcurrentHashMap<>(); // ← главный фикс
    private final SMPanel panel;
    private final ServerSettings ss = ServerSettings.getInstance();

    private int serverCounter = 0;

    public SMLogic(SMPanel panel) {
        this.panel = panel;
    }

    public void loadExistingServers() {
        File[] folders = ss.getServersPath().toFile().listFiles(File::isDirectory);
        if (folders != null) {
            for (File folder : folders) {
                String name = folder.getName();
                ServerCardSettings card = ss.loadServerCardSettings(name);
                panel.addServerCard(new ServerCard(card, this));
                updateServerCounter(name);
            }
        }
    }

    private void updateServerCounter(String folderName) {
        if (folderName.startsWith("server_")) {
            try {
                int num = Integer.parseInt(folderName.replace("server_", ""));
                serverCounter = Math.max(serverCounter, num + 1);
            } catch (NumberFormatException ignored) {
            }
        }
    }

    public void createNewServer(String motd, String version, int ram) {
        String serverName = "server_" + serverCounter++;
        Path serverPath = ss.getServerPath(serverName);

        if (Files.exists(serverPath)) {
            panel.showMessage("Папка уже существует!");
            return;
        }

        try {
            Files.createDirectories(serverPath);

            ServerCardSettings card = new ServerCardSettings(serverName, version, ram, motd);
            ss.saveServerCardSettings(serverName, card);

            // Показываем карточку сразу
            panel.addServerCard(new ServerCard(card, this));

            // Асинхронная подготовка файлов
            CompletableFuture.runAsync(() -> initializeServer(serverPath, card, version))
                    .thenRun(() -> System.out.println("✅ Сервер " + serverName + " создан"));

        } catch (IOException e) {
            e.printStackTrace();
            panel.showMessage("Ошибка создания: " + e.getMessage());
        }
    }

    private void initializeServer(Path serverPath, ServerCardSettings card, String version) {
        try {
            downloadJar(serverPath, version);
            createEula(serverPath);
            createBasicProperties(serverPath, card);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void downloadJar(Path serverPath, String version) {
        try (InputStream in = new URL(ServerSettings.SERVER_JAR_URL).openStream()) {
            Path target = serverPath.resolve(ServerSettings.SERVER_JAR_NAME);
            Files.copy(in, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void createEula(Path serverPath) {
        try {
            Files.writeString(serverPath.resolve(ServerSettings.EULA_TXT), "eula=true");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void createBasicProperties(Path serverPath, ServerCardSettings card) {
        Path prop = serverPath.resolve(ServerSettings.SERVER_PROPERTIES);
        Properties p = new Properties();
        p.setProperty("server-port", String.valueOf(card.getPort()));
        p.setProperty("motd", card.getMotd());
        p.setProperty("max-players", "20");
        p.setProperty("online-mode", "true");

        try (OutputStream os = Files.newOutputStream(prop)) {
            p.store(os, "Generated by launcher");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void startServerProcess(String serverName, ServerCardSettings card) {
        try {
            Path path = ss.getServerPath(serverName);
            String java = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";

            ProcessBuilder pb = new ProcessBuilder(
                    java,
                    "-Xmx" + card.getRamGB() + "G",
                    "-Xms" + Math.max(1, card.getRamGB() / 2) + "G",
                    "-jar", ServerSettings.SERVER_JAR_NAME,
                    "-nogui"
            ).directory(path.toFile());

            pb.redirectErrorStream(true);

            Process proc = pb.start();
            runningProcesses.put(serverName, proc);
            serverLogs.putIfAbsent(serverName, new StringBuilder());

            // Постоянный PrintWriter для отправки команд
            PrintWriter pw = new PrintWriter(
                    new OutputStreamWriter(proc.getOutputStream(), StandardCharsets.UTF_8), true);
            processInputs.put(serverName, pw);

        } catch (Exception e) {
            e.printStackTrace();
            panel.showMessage("Ошибка запуска: " + e.getMessage());
        }
    }

    public void startstopbutton(JButton btn, String serverName, JLabel status, ServerCardSettings card) {
        if (!runningProcesses.containsKey(serverName) || !runningProcesses.get(serverName).isAlive()) {
            // START
            btn.setText("Stop");
            btn.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
            status.setText("Запуск...");

            CompletableFuture.runAsync(() -> startServerProcess(serverName, card))
                    .thenRun(() -> SwingUtilities.invokeLater(() -> status.setText("Запущен")));
        } else {
            // STOP
            Process p = runningProcesses.get(serverName);
            status.setText("Выключение...");

            // Отправляем stop через постоянный PrintWriter
            PrintWriter writer = processInputs.get(serverName);
            if (writer != null) {
                writer.println("stop");
                writer.flush();
            }

            p.onExit().orTimeout(10, TimeUnit.SECONDS)
                    .thenRun(() -> finishStop(serverName, btn, status, false))
                    .exceptionally(ex -> {
                        if (p.isAlive()) p.destroyForcibly();
                        finishStop(serverName, btn, status, true);
                        return null;
                    });
        }
    }

    private void finishStop(String serverName, JButton btn, JLabel status, boolean forced) {
        runningProcesses.remove(serverName);
        activeLogReaders.remove(serverName);

        PrintWriter pw = processInputs.remove(serverName);
        if (pw != null) try {
            pw.close();
        } catch (Exception ignored) {
        }

        SwingUtilities.invokeLater(() -> {
            btn.setText("Start");
            btn.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
            status.setText(forced ? "Остановлен (принудительно)" : "Остановлен");
        });
    }

    public void LoggingToConsole(String serverName, JTextArea textArea) {
        StringBuilder history = serverLogs.computeIfAbsent(serverName, k -> new StringBuilder());

        // Восстанавливаем историю
        String currentLog;
        synchronized (history) {
            currentLog = history.toString();
        }
        SwingUtilities.invokeLater(() -> {
            textArea.setText(currentLog);
            textArea.setCaretPosition(textArea.getDocument().getLength());
        });

        Process p = runningProcesses.get(serverName);
        if (p == null || !p.isAlive() || !activeLogReaders.add(serverName)) return;

        CompletableFuture.runAsync(() -> {
            try (BufferedReader reader = new BufferedReader(
                    new InputStreamReader(p.getInputStream(), StandardCharsets.UTF_8))) {

                String line;
                while ((line = reader.readLine()) != null) {
                    String finalLine = line + "\n";
                    synchronized (history) {
                        history.append(finalLine);
                    }
                    SwingUtilities.invokeLater(() -> {
                        if (textArea.isDisplayable()) {
                            textArea.append(finalLine);
                            textArea.setCaretPosition(textArea.getDocument().getLength());
                        }
                    });
                }
            } catch (IOException e) {
                if (p.isAlive() && (e.getMessage() == null || !e.getMessage().contains("Stream closed"))) {
                    e.printStackTrace();
                }
            } finally {
                activeLogReaders.remove(serverName);
            }
        });
    }

    public void clearServerLog(String serverName) {
        serverLogs.put(serverName, new StringBuilder());
    }

    public void openEditServer(String serverName) {
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(panel);
        JDialog dlg = new JDialog(parent, "Редактирование — " + serverName, true);
        dlg.add(new EditServerCard(serverName, this));   // передаём this для сохранения
        dlg.pack();
        dlg.setLocationRelativeTo(parent);
        dlg.setVisible(true);
    }

    // Для EditServerCard — чтобы обновить карточку после сохранения
    public ServerCardSettings reloadCard(String serverName) {
        return ss.loadServerCardSettings(serverName);
    }

    public void SendToServer(String serverName, String command) {
        PrintWriter writer = processInputs.get(serverName);
        if (writer != null) {
            writer.println(command);
            writer.flush();
        }
    }
}