package gui.panels.server_manager_panel;

import gui.panels.server_manager_panel.cards.EditServerCard;
import gui.panels.server_manager_panel.cards.ServerCard;
import settings.ServerSettings;
import settings.ServerSettings.ServerCardSettings;

import javax.swing.*;
import java.awt.*;
import java.io.*;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.Properties;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;

public class SMLogic {

    private final ConcurrentHashMap<String, Process> runningProcesses = new ConcurrentHashMap<>();
    private final SMPanel panel;
    private final ServerSettings ss = ServerSettings.getInstance();

    private int serverCounter = 0;

    public SMLogic(SMPanel panel) {
        this.panel = panel;
    }

    public void loadExistingServers() {
        File[] folders = ss.getServersPath().toFile().listFiles(File::isDirectory);
        if (folders != null) {
            for (File folder : folders) {
                String name = folder.getName();
                ServerCardSettings card = ss.loadServerCardSettings(name);
                panel.addServerCard(new ServerCard(card, this));
                updateServerCounter(name);
            }
        }
    }

    private void updateServerCounter(String folderName) {
        if (folderName.startsWith("server_")) {
            try {
                int num = Integer.parseInt(folderName.replace("server_", ""));
                serverCounter = Math.max(serverCounter, num + 1);
            } catch (NumberFormatException ignored) {
            }
        }
    }

    public void createNewServer() {
        String serverName = "server_" + serverCounter++;
        Path serverPath = ss.getServerPath(serverName);

        if (Files.exists(serverPath)) {
            panel.showMessage("Папка уже существует!");
            return;
        }

        try {
            Files.createDirectories(serverPath);

            ServerCardSettings card = new ServerCardSettings(serverName);
            ss.saveServerCardSettings(serverName, card);

            // Показываем карточку сразу
            panel.addServerCard(new ServerCard(card, this));

            // Асинхронная подготовка файлов
            CompletableFuture.runAsync(() -> initializeServer(serverPath, card))
                    .thenRun(() -> System.out.println("✅ Сервер " + serverName + " создан"));

        } catch (IOException e) {
            e.printStackTrace();
            panel.showMessage("Ошибка создания: " + e.getMessage());
        }
    }

    private void initializeServer(Path serverPath, ServerCardSettings card) {
        try {
            downloadJar(serverPath);
            createEula(serverPath);
            createBasicProperties(serverPath, card);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void downloadJar(Path serverPath) {
        try (InputStream in = new URL(ServerSettings.SERVER_JAR_URL).openStream()) {
            Path target = serverPath.resolve(ServerSettings.SERVER_JAR_NAME);
            Files.copy(in, target, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void createEula(Path serverPath) {
        try {
            Files.writeString(serverPath.resolve(ServerSettings.EULA_TXT), "eula=true");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void createBasicProperties(Path serverPath, ServerCardSettings card) {
        Path prop = serverPath.resolve(ServerSettings.SERVER_PROPERTIES);
        Properties p = new Properties();
        p.setProperty("server-port", String.valueOf(card.getPort()));
        p.setProperty("motd", card.getMotd());
        p.setProperty("max-players", "20");
        p.setProperty("online-mode", "true");

        try (OutputStream os = Files.newOutputStream(prop)) {
            p.store(os, "Generated by launcher");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void startServerProcess(String serverName, ServerCardSettings card) {
        try {
            Path path = ss.getServerPath(serverName);
            String java = System.getProperty("java.home") + File.separator + "bin" + File.separator + "java";

            ProcessBuilder pb = new ProcessBuilder(
                    java,
                    "-Xmx" + card.getRamGB() + "G",
                    "-Xms" + Math.max(1, card.getRamGB() / 2) + "G",
                    "-jar", ServerSettings.SERVER_JAR_NAME,
                    "-nogui"
            ).directory(path.toFile());
            

            Process proc = pb.start();
            runningProcesses.put(serverName, proc);


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void startstopbutton(JButton btn, String serverName, JLabel status, ServerCardSettings card) {
        if (!runningProcesses.containsKey(serverName)) {
            // START
            btn.setText("Stop");
            btn.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
            status.setText("Запуск...");

            CompletableFuture.runAsync(() -> startServerProcess(serverName, card))
                    .thenRun(() -> SwingUtilities.invokeLater(() -> status.setText("Запущен")));
        } else {
            // STOP
            Process p = runningProcesses.get(serverName);
            if (p != null && p.isAlive()) {
                try (OutputStreamWriter w = new OutputStreamWriter(p.getOutputStream())) {
                    w.write("stop\n");
                    w.flush();
                    status.setText("Выключение...");

                    // Запускаем ожидание в фоновом потоке
                    p.onExit().thenRun(() -> {
                        // SwingUtilities нужен, если вы используете Swing для обновления UI
                        runningProcesses.remove(serverName);   // ← добавь эту строку
                        javax.swing.SwingUtilities.invokeLater(() -> {
                            btn.setText("Start");
                            btn.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
                            status.setText("Остановлен");
                        });
                    });

                } catch (IOException e) {
                    p.destroy();
                    btn.setText("Start");
                    btn.setBorder(BorderFactory.createLineBorder(Color.GREEN, 3));
                    status.setText("Остановлен (принудительно)");
                }
            }
        }
    }

    public void openEditServer(String serverName) {
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(panel);
        JDialog dlg = new JDialog(parent, "Редактирование — " + serverName, true);
        dlg.add(new EditServerCard(serverName, this));   // передаём this для сохранения
        dlg.pack();
        dlg.setLocationRelativeTo(parent);
        dlg.setVisible(true);
    }

    // Для EditServerCard — чтобы обновить карточку после сохранения
    public ServerCardSettings reloadCard(String serverName) {
        return ss.loadServerCardSettings(serverName);
    }

    public void SendToServer(String serverName, String command) {
        if (runningProcesses.containsKey(serverName)) {
            Process p = runningProcesses.get(serverName);
            if (p != null && p.isAlive()) {
                try (OutputStreamWriter w = new OutputStreamWriter(p.getOutputStream())) {
                    w.write(command + "\n");
                    w.flush();

                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    public void LoggingToConsole(String serverName, JTextArea textArea) {
        if (runningProcesses.containsKey(serverName)) {
            Process p = runningProcesses.get(serverName);
            if (p != null && p.isAlive()) {
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        textArea.append(line + "\n");
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

    }
}