# File logging settings
file.enabled=true
file.directory=logs
file.level=ALL
file.thread = false
file.pattern=app_%d{yyyy-MM-dd}.log
file.max.size=10485760
file.max.files=5
file.append=true

# Console logging settings
console.enabled=true
console.level=WARNING
console.color=true
console.thread=false
console.timestamp=true

# App settings
app.name=SwingCoding